### PR TITLE
Rename room folder

### LINKED ISSUE #80: Re-add skeleton in center of section B

### LINKED ISSUE #92: Add section B gift shop reward

### LINKED ISSUE #103: Two section B coins have the same buddha face

### LINKED ISSUE #104: Rename room folder
Don't use double underscores - ES has trouble parsing them

Let everyone know of the change

### PR DESCRIPTION
**Pull request by paulkim26**
Fixes #104 
Fixes #103 
Fixes #92 
Fixes #80

### CODE REVIEW

**Comment by paulkim26** [comment]
Screenshot 2023-06-16 233108
Re-added whale skeleton to section b center. Decimated to ~6K faces

**Comment by paulkim26** [comment]
Screenshot 2023-06-16 233145
Added missing plane medallion texture

**Comment by paulkim26** [comment]
Screenshot 2023-06-16 233239
Added section B gift to gift shop, ready to be scaled + placed in a case

**Comment by paulkim26** [comment]
Screenshot 2023-06-16 233333
Moved butterfly so it doesn't clip with medallion

**Review by chazzybuch — APPROVED** [review]

**Pull request merged**
