### PR TITLE
Added DNA puzzle hint

### LINKED ISSUE #150: DNA puzzle - add in-game hint(s)

### LINKED ISSUE #181: L02. Button is clickable
image

### LINKED ISSUE #186: History Centered Zoomables hard to click
The colliders of the frames might need to be disabled to properly target the zoomable text

### LINKED ISSUE #194: "Collab Museum" prop on creator card stand should not be button
image

### PR DESCRIPTION
**Pull request by paulkim26**
Fixes #194 
Fixes #186 
Fixes #181 
Fixes #150

### CODE REVIEW

**Comment by paulkim26** [comment]
Replaced cargo ship + parquet models with version provided by Robin. Joins individual objects in blender into 1 object. Dramatically reduces load time.

**Comment by paulkim26** [comment]
Fixes #195 
Fixed regression with #164 (not sure when regression was re-introduced)

**Comment by paulkim26** [comment]
Decimated whale tunnel from 69k to 14k faces

**Review by FranchNotFrench — APPROVED** [review]
Looks good

**Pull request merged**
